version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - CamiloGarciaLaRotta
      - titoine54
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    default_labels:
      - "dependencies"
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - CamiloGarciaLaRotta
      - titoine54
    commit_message:
      prefix: "fix"
    default_labels:
      - "dependencies"
